// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOB-fTxCcenrlk9AqGI3LfjJYW70HBC1o',
    appId: '1:756190928045:web:b31886f77a5c69b00a7a24',
    messagingSenderId: '756190928045',
    projectId: 'anuhhav-test-enter',
    authDomain: 'anuhhav-test-enter.firebaseapp.com',
    storageBucket: 'anuhhav-test-enter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18Q8VZOdevJlTKhNvcw-WLJ970aRVY04',
    appId: '1:756190928045:android:9c27d9aae26b14c60a7a24',
    messagingSenderId: '756190928045',
    projectId: 'anuhhav-test-enter',
    storageBucket: 'anuhhav-test-enter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MQZ-owBzLu2TsESFi3cOlV_ZH-qLu9o',
    appId: '1:756190928045:ios:3d089fc8e78da3200a7a24',
    messagingSenderId: '756190928045',
    projectId: 'anuhhav-test-enter',
    storageBucket: 'anuhhav-test-enter.appspot.com',
    iosBundleId: 'com.example.mokshayani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2MQZ-owBzLu2TsESFi3cOlV_ZH-qLu9o',
    appId: '1:756190928045:ios:3d089fc8e78da3200a7a24',
    messagingSenderId: '756190928045',
    projectId: 'anuhhav-test-enter',
    storageBucket: 'anuhhav-test-enter.appspot.com',
    iosBundleId: 'com.example.mokshayani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOB-fTxCcenrlk9AqGI3LfjJYW70HBC1o',
    appId: '1:756190928045:web:c1372640015b442c0a7a24',
    messagingSenderId: '756190928045',
    projectId: 'anuhhav-test-enter',
    authDomain: 'anuhhav-test-enter.firebaseapp.com',
    storageBucket: 'anuhhav-test-enter.appspot.com',
  );
}
